/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FigureDisplay: typeof import('./../../components/FigureDisplay/FigureDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./../../components/ScrollArea/ScrollArea.vue')['default']
    SplitPane: typeof import('./../../components/SplitPane/SplitPane.vue')['default']
  }
}
