/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const useBus: typeof import('../../hooks/useBus')['useBus']
  const usePaths: typeof import('../../hooks/usePaths')['usePaths']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { SendKeyCheck, OnKeyCheck, InvokeKeyCheck } from '../../hooks/useBus'
  import('../../hooks/useBus')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly useBus: UnwrapRef<typeof import('../../hooks/useBus')['useBus']>
    readonly usePaths: UnwrapRef<typeof import('../../hooks/usePaths')['usePaths']>
  }
}