/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const useClientStore: typeof import('../../stores/client')['useClientStore']
  const useSystemStore: typeof import('../../stores/system')['useSystemStore']
  const useWindowStore: typeof import('../../stores/window')['useWindowStore']
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly useClientStore: UnwrapRef<typeof import('../../stores/client')['useClientStore']>
    readonly useSystemStore: UnwrapRef<typeof import('../../stores/system')['useSystemStore']>
    readonly useWindowStore: UnwrapRef<typeof import('../../stores/window')['useWindowStore']>
  }
}